minimum_single: 5
minimum_multiple: 2
disable_search_threshold: 0
minimum_width: 200
jquery_selector: 'select:visible'
search_contains: true
disable_search: false
allow_single_deselect: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  seven: '0'
  ucsftest: '0'
chosen_include: 2
_core:
  default_config_hash: JUHKHJeHl1bWXY41HMIcDR-VmAWvJ4OJycDubCkIeDU
