field.widget.settings.select_other_widget:
  type: mapping
  label: 'Select or other widget display format settings'
  mapping:
    available_options:
      type: string
      label: 'Type of select form element'
