<?php

/**
 * Implements hook_theme_registry_alter().

function y3ti_locations_map_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'y3ti_locations_map');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

function y3ti_locations_map_field_widget_addressfield_standard_form_alter(&$element, &$form_state, $context) {
    $element['#type'] = 'container';
}

function y3ti_locations_map_preprocess_page(&$vars, $hook) {
  if(isset($vars['node']) && $vars['node']->type == 'map'){
    $inside_node = '';
    if(isset($vars['page']) && sizeof($vars['page']['content']['system_main']['nodes'])) {
      $inside_node = reset($vars['page']['content']['system_main']['nodes']);
    }
    if(isset($inside_node) && isset($inside_node['field_collec_locations']['#view_mode']) && $inside_node['field_collec_locations']['#view_mode'] == 'full') {
      drupal_add_js(array('nid' => $vars['node']->nid), 'setting');
      drupal_add_css(drupal_get_path('module', 'y3ti_locations_map') . '/css/y3ti_locations_map.css');
      drupal_add_js(drupal_get_path('module', 'y3ti_locations_map') . '/js/y3ti_locations_map.js');
    }
  }
}
 */
