version: 1.2.0
services:
  - mysql
  - php:
        version: 7.1
variables:
  global:
cde-databases:
  - ucsfpa8
events:
  build:
    steps:
      - setup:
          type: script
          script:
            - echo "completed"
            - if [ "$PIPELINE_WEBHOOK_EVENT" == "PULL_REQUEST" ]; then echo "pull request made"; fi
  post-deploy:
    steps:
      # Deploy the build artifact to a Cloud on-demand environment.
      - deploy:
          # Build on Pull Request only (but not for the dev branch since it already has its own Sand environment).
          script:
            - if [ "$PIPELINE_WEBHOOK_EVENT" == "PULL_REQUEST" ] && [ "$SOURCE_VCS_PATH" != "dev" ]; then
            - echo "Create/Update a new On Demand Environment for $PIPELINE_DEPLOY_VCS_PATH"
            - pipelines-deploy
            - pipelines-sync-dbs ucsfpa8
            - fi
          # For the dev git branch, only pull the database.
          script:
            - if [ "$SOURCE_VCS_PATH" == "dev" ]; then
            - pipelines-sync-dbs ucsfpa8
            - fi

  # When a GitHub pull request is merged, this deletes the corresponding ODE.
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy

  # When a GitHub pull request is closed, this deletes the corresponding ODE.
  pr-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
