version: 1.2.0
services:
  - mysql
  - php:
        version: 7.1
variables:
  global:
events:
  build:
    steps:
      - setup:
          type: script
          script:
            - echo "completed"
