version: 1.2.0
services:
  - mysql
  - php:
        version: 7.1
variables:
  global:
cde-databases:
  - ucsfpa8
events:
  build:
    steps:
      - setup:
          type: script
          script:
            - echo "completed"
            - echo $PIPELINE_DEPLOY_VCS_PATH
            - echo $SOURCE_VCS_PATH
            - echo $DEPLOY_VCS_PATH
  post-deploy:
    steps:
      # Deploy the build artifact to a Cloud on-demand environment.
      - deploy:
          script:
            - pipelines-deploy
            - pipelines-sync-dbs ucsfpa8

  # When a GitHub pull request is merged, this deletes the corresponding ODE.
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy

  # When a GitHub pull request is closed, this deletes the corresponding ODE.
  pr-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
