version: 1.2.0
services:
  - mysql
  - php:
        version: 7.1
variables:
  global:
#    SLACK_HOSTNAME: "uctech.slack.com"
#    SLACK_TOKEN:
#      secure: U48EOVjDl+h+QRi$x3kpGwBIc27rKqCblXqkv2MxMBDyV+Pas3x...
#    SLACK_CHANNEL: "#ucsf-www-ucsf-edu"
events:
  build:
    steps:
      - composer:
          type: script
          script:
            - composer install
      - unit_tests:
                type: script
                script:
                  - echo "unit tests completed"
