version: 1.0.1
services:
  - mysql
variables:
  global:
events:
  build:
    steps:
      - setup:
          type: script
          script:
            - git submodule sync
            - git submodule update --init
            - echo "completed"
