<?php

/**
 * @file
 * Contains ucsf_applenews.module.
 */

use ChapterThree\AppleNewsAPI\Document\ContentInset;
use ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout;
use ChapterThree\AppleNewsAPI\Document\Margin;
use ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle;
use ChapterThree\AppleNewsAPI\Document\Styles\DropCapStyle;
use ChapterThree\AppleNewsAPI\Document\Styles\TextStyle;

/**
 * Component layouts.
 *
 * Entity fields, etc. that are normalized via custom normalizers don't get
 * their layout from config. I've centralized them here.
 */

/**
 * Generates layout for gallery components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout
 */
function _ucsf_applenews_gallery_component_layout() {
  $layout = new ComponentLayout();
  $layout
    ->setColumnStart(1)
    ->setColumnSpan(7)
    ->setMargin(new Margin(25, 25))
    ->setIgnoreDocumentMargin('both');
  return $layout;
}

/**
 * Generates layout for header components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout
 */
function _ucsf_applenews_header_component_layout() {
  $layout = new ComponentLayout();
  $layout
    ->setMargin(new Margin(15, 15));
  return $layout;
}

/**
 * Generates layout for photo components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout
 */
function _ucsf_applenews_photo_component_layout() {
  $inset = new ContentInset();
  $inset
    ->setBottom(FALSE)
    ->setLeft(FALSE)
    ->setRight(FALSE)
    ->setTop(FALSE);
  $layout = new ComponentLayout();
  $layout
    ->setColumnStart(0)
    ->setColumnSpan(9)
    ->setMargin(new Margin(15, 15))
    ->setContentInset($inset)
    ->setIgnoreDocumentMargin('both')
    ->setIgnoreDocumentGutter('both');
  return $layout;
}

/**
 * Generates layout for quote components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout
 */
function _ucsf_applenews_quote_component_layout() {
  $inset = new ContentInset();
  $inset
    ->setBottom(FALSE)
    ->setLeft(FALSE)
    ->setRight(FALSE)
    ->setTop(FALSE);
  $layout = new ComponentLayout();
  $layout
    ->setColumnStart(3)
    ->setColumnSpan(4)
    ->setMargin(new Margin(15, 15))
    ->setContentInset($inset);
  return $layout;
}

/**
 * Generates layout for title components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout
 */
function _ucsf_applenews_title_component_layout() {
  $inset = new ContentInset();
  $inset
    ->setBottom(FALSE)
    ->setLeft(FALSE)
    ->setRight(FALSE)
    ->setTop(FALSE);
  $layout = new ComponentLayout();
  $layout
    ->setColumnStart(0)
    ->setColumnSpan(7)
    ->setMargin(new Margin(15, 8))
    ->setContentInset($inset)
    ->setIgnoreDocumentMargin('none')
    ->setIgnoreDocumentGutter('none');
  return $layout;
}

/**
 * Generates layout for video components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout
 */
function _ucsf_applenews_video_component_layout() {
  $inset = new ContentInset();
  $inset
    ->setBottom(FALSE)
    ->setLeft(FALSE)
    ->setRight(FALSE)
    ->setTop(FALSE);
  $layout = new ComponentLayout();
  $layout
    ->setColumnStart(0)
    ->setColumnSpan(9)
    ->setMargin(new Margin(15, 15))
    ->setContentInset($inset)
    ->setIgnoreDocumentMargin('both')
    ->setIgnoreDocumentGutter('both');
  return $layout;
}

/**
 * Component text styles.
 *
 * @todo Migrate to config via admin/config/services/applenews/text-style/add
 */

/**
 * Generates base link style for components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\TextStyle
 */
function _ucsf_applenews_base_component_link_style() {
  $link_style = new TextStyle();
  $link_style
    ->setFontName('HelveticaNeue-Medium')
    ->setFontSize(18)
    ->setTextColor('#0071AD')
    ->setUnderline(FALSE);
  return $link_style;
}

/**
 * Generates base text style for components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle
 */
function _ucsf_applenews_base_component_text_style() {
  $style = new ComponentTextStyle();
  $style
    ->setFontName('HelveticaNeue')
    ->setHyphenation(FALSE)
    ->setStrikethrough(FALSE)
    ->setTextAlignment('left')
    ->setTextColor('#000000')
    ->setTextTransform('none')
    ->setUnderline(FALSE)
    ->setVerticalAlignment('baseline');
  return $style;
}

/**
 * Generates text style for author components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle
 */
function _ucsf_applenews_author_component_text_style() {
  $style = _ucsf_applenews_base_component_text_style();
  $style
    ->setFontName('HelveticaNeue-Italic')
    ->setFontSize(14)
    ->setTextColor('#646464');
  return $style;
}

/**
 * Generates text style for body components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle
 */
function _ucsf_applenews_body_component_text_style($dropcap = TRUE) {
  $style = _ucsf_applenews_base_component_text_style();
  $style
    ->setLinkStyle(_ucsf_applenews_base_component_link_style())
    ->setFontSize(18)
    ->setLineHeight(26)
    ->setTextColor('#000000');
  if ($dropcap) {
    $dropcap_style = new DropCapStyle(2);
    $dropcap_style
      ->setNumberOfCharacters(1)
      ->setFontName('HelveticaNeue-Light')
      ->setTextColor('#0071AD');
    $style->setDropCapStyle($dropcap_style);
  }
  return $style;
}

/**
 * Generates text style for heading components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle
 */
function _ucsf_applenews_heading_component_text_style($level) {
  $style = _ucsf_applenews_base_component_text_style();
  $style
    ->setFontName('HelveticaNeue-Bold');
  switch ($level) {

    case 1:
      $style->setFontSize(24);
      break;

    case 2:
      $style->setFontSize(20);
      break;

    case 3:
      $style->setFontSize(18);
      break;

    case 4:
      $style->setFontSize(14);
      break;

    case 5:
      $style->setFontSize(12);
      break;

    case 6:
      $style->setFontSize(10);
      break;

  }
  return $style;
}

/**
 * Generates text style for title components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle
 */
function _ucsf_applenews_title_component_text_style() {
  $style = _ucsf_applenews_base_component_text_style();
  $style
    ->setFontName('HelveticaNeue-Light')
    ->setFontSize(40);
  return $style;
}

/*
"text": "Study senior author Edward Chang, MD, has been studying how the...",
"role": "caption",
"format": "html",
"layout": {
"columnStart": 0,
"columnSpan": 7,
"margin": { "top": 10, "bottom": 15 },
"contentInset": {
"top": false,
"right": false,
"bottom": false,
"left": false
},
"paragraphSpacingBefore": 12,
"paragraphSpacingAfter": 12
},
"textStyle": {
"fontSize": 11,
"textAlignment": "left",
"lineHeight": 16,
"textColor": "#0071AD",
"hyphenation": false,
"linkStyle": {
"fontName": "HelveticaNeue-Light",
"fontSize": 11,
"textColor": "#0071AD",
"underline": false
 */


/**
 * Generates text style for quote components.
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle
 */
function _ucsf_applenews_quote_component_text_style() {
  $style = _ucsf_applenews_base_component_text_style();
  $style
    ->setFontName('HelveticaNeue-Light')
    ->setFontSize(24)
    ->setLineHeight(36)
    ->setTextColor('#0071AD')
    ->setTextAlignment('center');
  return $style;
}

/**
 * Generates a below the image caption layout.
 * @return \ChapterThree\AppleNewsAPI\Document\Styles\ComponentTextStyle
 */
function _ucsf_applenews_text_caption_style() {
  $style = _ucsf_applenews_base_component_text_style();
  $style
    ->setFontName('HelveticaNeue-Medium')
    ->setFontSize(14)
    ->setLineHeight(19)
    ->setTextColor('#646464')
    ->setTextAlignment('left');

  return $style;
}

/**
 *
 *
 * @return \ChapterThree\AppleNewsAPI\Document\Layouts\ComponentLayout
 */
function _ucsf_applenews_text_caption_layout() {
  $inset = new ContentInset();
  $inset
    ->setBottom(FALSE)
    ->setLeft(FALSE)
    ->setRight(FALSE)
    ->setTop(FALSE);
  $layout = new ComponentLayout();
  $layout
    ->setColumnStart(0)
    ->setColumnSpan(7)
    ->setMargin(new Margin(10, 15))
    ->setContentInset($inset);

  return $layout;
}