<?php

/**
 * @file
 * Contains ucsf_applenews.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() on behalf of ucsf_applenews.module.
 */
function ucsf_applenews_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change form id here
  if ($form_id == 'node_article_edit_form' &&
    !empty($form['field_apple_news']['widget'][0]['message']['#markup'])
  ) {

    /** @var \Drupal\node\NodeForm $form_object */
    $form_object = $form_state->getFormObject();
    /** @var \Drupal\node\Entity\Node $node */
    $node = $form_object->getEntity();

    /** @var \Drupal\migrate\Plugin\MigrationPluginManager $migration_manager */
    $migration_manager = Drupal::service('plugin.manager.migration');
    /** @var \Drupal\migrate\Plugin\Migration $migration */
    $migration = reset($migration_manager->createInstances(['news_content']));
    /** @var \Drupal\migrate\Plugin\migrate\id_map\Sql $map */
    $map = $migration->getIdMap();
    $source_id = $map->lookupSourceId(['nid' => $node->id()]);

    if (isset($source_id['nid'])) {

      $base_url = \Drupal::config('ucsf_applenews.settings')
        ->get('migrate.legacy_base_url');
      $url = \Drupal\Core\Url::fromUri(
        rtrim($base_url, '/') .
        '/admin/structure/publish-to-apple-news/types/11/preview');
      $form['field_apple_news']['widget'][0]['message']['#markup'] .=  t('To view export from legacy site, go to', []);

    }


  }
}
