condition.plugin.token_matcher:
  type: condition.plugin
  mapping:
    token_match:
      type: string
    value_match:
      type: string
    check_empty:
      type: boolean
    use_regex:
      type: boolean
