version: "3.9"

services:
  cli:
    environment:
      - API_KEY
      - API_SECRET
      - ACQUIA_ENV_ID
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MEMORY_LIMIT=1G
      - UPLOAD_LIMIT=1G
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}