version: "3.9"

services:
  cli:
    environment:
      - IS_DOCKSAL=1
      - XDEBUG_ENABLED=1
      - SOLR_CORE
      - API_KEY
      - API_SECRET
      - ACQUIA_ENV_ID
      - MODULES_ENABLED
      - MODULES_DISABLED
  pma:
    hostname: pma
    image: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MEMORY_LIMIT=1G
      - UPLOAD_LIMIT=1G
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
