<?php

/**
 * @file
 * Apple News module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\migrate\MigrateSkipRowException;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_entity_insert().
 */
function applenews_entity_insert(EntityInterface $entity) {

  try {
    /** @var \Drupal\applenews\ApplenewsManager $manager */
    $manager = \Drupal::service('applenews.manager');
    // On successful post, save response details on entity.
    $manager->postArticle($entity);
  }
  catch (\Exception $e) {
    \Drupal::logger('applenews')->error(t('Error while trying to create an article in Apple News: @error', ['@error' => $e->getMessage()]));
  }
}

/**
 * Implements hook_entity_update().
 */
function applenews_entity_update(EntityInterface $entity) {

  try {
    /** @var \Drupal\applenews\ApplenewsManager $manager */
    $manager = \Drupal::service('applenews.manager');
    // On successful post, save response details on entity.
    $manager->postArticle($entity);
  }
  catch (\Exception $e) {
    \Drupal::logger('applenews')->error(t('Error while trying to update an article in Apple News: @error', ['@err' => $e->getMessage()]));
  }
}

/**
 * Implements hook_entity_delete().
 */
function applenews_entity_delete(EntityInterface $entity) {

  try {
    /** @var \Drupal\applenews\ApplenewsManager $manager */
    $manager = \Drupal::service('applenews.manager');
    // On successful post, save response details on entity.
    $manager->delete($entity);
  }
  catch (\Exception $e) {
    \Drupal::logger('applenews')->error(t('Error while trying to delete an article in Apple News: @error', ['@err' => $e->getMessage()]));
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function applenews_migration_plugins_alter(array &$migrations) {
  // Add field mapping for applenews node fields.
  $applenews_manager = \Drupal::service('applenews.manager');
  $fields = $applenews_manager->getFields('node');
  if (empty($fields)) {
    return;
  }

  foreach ($fields as $field_instance_id => $field_instance_config) {
    foreach ($field_instance_config['bundles'] as $bundle) {
      if (isset($migrations['d7_node:' . $bundle])) {
        // We could map status to publish_flag but that would trigger publishing
        // the article to Applenews so we hardcode it to+ 0.
        $migrations['d7_node:' . $bundle]['source']['constants']['applenews_status'] = 0;
        $migrations['d7_node:' . $bundle]['process'] += [
          $field_instance_id . '/status' => 'constants/applenews_status',
          $field_instance_id . '/channels' => 'applenews_channels',
          $field_instance_id . '/is_preview' => 'applenews_is_preview',
          $field_instance_id . '/template' => 'applenews_template',
        ];
      }
    }
  }

}

/**
 * Implements hook_migrate_prepare_row().
 */
function applenews_migrate_prepare_row(
  Row $row,
  MigrateSourceInterface $source,
  MigrationInterface $migration
) {
  if ($source->getPluginId() == 'd7_node') {
    $data = $source->getDatabase()->query('select data from {applenews_entity_settings} where entity_type = :type and entity_id = :entity_id', [':type' => 'node', ':entity_id' => $row->getSourceProperty('nid')])->fetchField();
    if (!empty($data)) {
      // Extract channels and is_preview from the data field.
      $data = unserialize($data);
      $row->setSourceProperty('applenews_channels', serialize($data['channels']));
      $row->setSourceProperty('applenews_is_preview', (int) $data['is_preview']);

      // Find a template for this node's content type.
      $template_ids = \Drupal::entityTypeManager()
        ->getStorage('applenews_template')
        ->getQuery()
        ->condition('node_type', 'blog')
        ->execute();
      if (empty($template_ids)) {
        throw new MigrateSkipRowException(sprintf('You need to create an Applenews template for content type %s.', $row->getSourceProperty('type')));
      }
      $row->setSourceProperty('applenews_template', reset($template_ids));
    }
  }
}
