sitefarm.admin_index:
  title: 'SiteFarm'
  route_name: sitefarm.admin_index
  description: 'SiteFarm'
  parent: system.admin_config

sitefarm.cache_clear_form:
  title: 'Clear Cache'
  route_name: sitefarm.cache_clear_form
  description: 'Clear the site Cache.'
  parent: sitefarm.admin_index
  weight: 99

sitefarm.metatag_frontpage:
  title: 'Frontpage SEO'
  route_name: entity.metatag_defaults.edit_form
  route_parameters:
    metatag_defaults: front
  description: 'Configure Search Engine Optimization options for the Home page.'
  parent: sitefarm.admin_index
  weight: 99

sitefarm.fix_broken_links:
  title: 'Fix Broken Page Links'
  route_name: redirect_404.fix_404
  description: 'Fix Broken 404 Page Links by adding redirects.'
  parent: sitefarm.admin_index
  weight: 99

sitefarm.restrict_configuration_pages:
  title: 'Restrict Configuration Pages'
  route_name: sitefarm.restrict_configuration_pages
  description: 'Alter the configuration pages which should be hidden from Site Managers.'
  parent: sitefarm.admin_index
  weight: 100

sitefarm.customize_block_types:
  title: 'Configure Custom Block Types'
  route_name: sitefarm.customize_block_types
  description: 'Administer configurations for custom block types.'
  parent: sitefarm.admin_index
  weight: 101
