# Schema for the configuration files of the Acquia Content Hub module.
acquia_contenthub.admin_settings:
  type: config_object
  label: 'Acquia Content Hub admin settings'
  mapping:
    hostname:
      type: string
      label: "Content Hub API Hostname."
    api_key:
      type: string
      label: "Content Hub API Key."
    secret_key:
      type: string
      label: "Content Hub API Secret Key."
    rewrite_domain:
      type: string
      label: "Rewrite current domain to the domain set in this variable to 'fool' content hub where to fetch the content from. Useful with tunnels such as ngrok."
    client_name:
      type: string
      label: "Name of the current site as known in Acquia Content Hub."
    origin:
      type: string
      label: "Content Hub Token for this site."

acquia_contenthub.entity_config:
  type: config_object
  label: 'Acquia Content Hub entity configuration settings'
  mapping:
    user_role:
      type: string
      label: "Role to use when converting an Entity to a CDF with or without Metadata"
    dependency_depth:
      type: integer
      label: "The maximum level of dependencies to collect for exporting entities"
    use_block_content_view_builder:
      type: boolean
      label: "If true, uses block_content view builder instead of block plugin render."
    export_with_queue:
      type: integer
      label: "Whether to export entities using the queue"
    export_queue_entities_per_item:
      type: integer
      label: "Number of top-level entities that will be included in each item."
    export_queue_batch_size:
      type: integer
      label: "Number of items that will be processed in the same batch."
    export_queue_waiting_time:
      type: integer
      label: "Waiting time in seconds between processing queue items."
    delete_mismatching_translations:
      type: integer
      label: "Delete mismatching translations when importing content."

acquia_contenthub.entity.*:
  type: config_entity
  label: 'Acquia Content Hub entity type configuration'
  mapping:
    id:
      type: string
      label: 'REST resource config ID'
    bundles:
      type: sequence
      label: 'Entity bundle configuration'
      sequence:
        type: mapping
        label: 'A specific entity bundle configuration'
        mapping:
          enable_index:
            type: boolean
            label: 'Defines if this is being sent to Content Hub.'
          enable_viewmodes:
            type: boolean
            label: 'Defines if we want to index view modes to Content Hub.'
          rendering:
            type: sequence
            label: 'Defines which view modes are enabled for this entity bundle.'
            sequence:
              type: string
              label: 'An enabled view mode'
          preview_image_field:
            type: string
            label: 'A mapping string to the field which holds the image file.'
          preview_image_style:
            type: string
            label: 'A image style machine name.'
