#!/usr/bin/env bash

## Export database to file repo/db/[dbname].sql (will overwrite existing)
##
## Usage: fin dbexport [dbname]

EXPORT_PATH="${PROJECT_ROOT}/db"

fin db dump --db=$1 $EXPORT_PATH/$1.sql 