<?php

/**
 * @file
 * Contains ucsf_google_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ucsf_google_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ucsf_google_search module.
    case 'help.page.ucsf_google_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Google Custom Search for UCSF') . '</p>';
      return $output;

    default:
  }
}

