name: Domain Site Settings
type: module
description: 'Basic Site Setting for Domains.'
dependencies:
  - domain:domain
  - domain:domain_config

package: Domain
core_version_requirement: ^8.8 || ^9
configure: domain_site_settings.list

# Information added by Drupal.org packaging script on 2021-07-20
version: '8.x-1.4'
project: 'domain_site_settings'
datestamp: 1626772895
