field.formatter.settings.amp_iframe:
  type: mapping
  label: 'AMP iFrame field formatter settings'

field.formatter.settings.amp_text:
  type: mapping
  label: 'AMP Text field formatter settings'

field.formatter.settings.amp_text_summary_or_trimmed:
  type: mapping
  label: 'AMP Summary or Trimmed field formatter settings'
  mapping:
    trim_length:
      type: integer
      label: 'Trim length'

field.formatter.settings.amp_text_trimmed:
  type: mapping
  label: 'AMP Trimmed Text field formatter settings'
  mapping:
    trim_length:
      type: integer
      label: 'Trim length'

field.formatter.settings.amp_image:
  type: mapping
  label: 'AMP image field formatter settings'
  mapping:
    image_style:
      type: string
      label: 'Image style'
    image_link:
      type: string
      label: 'Link image to'
    layout:
      type: string
      label: 'AMP layout'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'

field.formatter.settings.amp_image_carousel:
  type: mapping
  label: 'AMP image carousel formatter settings'
  mapping:
    type:
      type: string
      label: 'Carousel type'
    layout:
      type: string
      label: 'AMP layout'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    autoplay:
      type: string
      label: 'Autoplay'
    controls:
      type: string
      label: 'Controls'
    loop:
      type: string
      label: 'Loop'

field.formatter.settings.amp_video:
  type: mapping
  label: 'AMP video file field formatter settings'
  mapping:
    use_description_as_link_text:
      type: boolean
      label: 'Replace the file name by its description when available'
    layout:
      type: string
      label: 'AMP layout'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    autoplay:
      type: string
      label: 'Autoplay'
    controls:
      type: string
      label: 'Controls'
    loop:
      type: string
      label: 'Loop'

views.style.html_list:
  type: views_style
  label: 'AMP Views Carousel settings'
  mapping:
    wrapper_class:
      type: string
      label: 'Wrapper class'
    type:
      type: string
      label: 'Carousel type'
    layout:
      type: string
      label: 'Layout'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'height'
    autoplay:
      type: boolean
      label: 'Autoplay'
    controls:
      type: boolean
      label: 'Controls'
    loop:
      type: boolean
      label: 'Loop'

field.formatter.settings.amp_social_post_formatter:
  type: mapping
  label: 'AMP social post field formatter settings'
  mapping:
    use_description_as_link_text:
      type: boolean
      label: 'Replace the file name by its description when available'
    layout:
      type: string
      label: 'AMP layout'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    data-embed-as:
      type: string
      label: 'Embed as'
    data-align-center:
      type: string
      label: 'Align center'
    provider:
      type: string
      label: 'Provider'
    placeholder:
      type: string
      label: 'Placeholder'
