amp.analytics.settings:
  type: mapping
  label: 'AMP Analytics settings'
  mapping:
    langcode:
      type: string
    amp_gtm:
      type: string
      label: 'Google Tag Manager id'
    amp_pixel:
      type: boolean
      label: 'Whether the amp-pixel should be included'
    amp_pixel_domain_name:
      type: string
      label: 'Domain name of tracking pixel'
    amp_pixel_query_string:
      type: string
      label: 'Query path for domain of tracking pixel'
    amp_pixel_random_number:
      type: boolean
      label: 'Whether to include a random number in the URL'
    google_analytics_id:
      type: string
      label: 'Google Analytics Web Property ID'

