acquia_contenthub_subscriber.contenthub_filter.*:
  type: config_entity
  label: 'ContentHub Filter'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Name'
    publish_setting:
      type: string
      label: 'Publish Setting'
    search_term:
      type: string
      label: 'Search Term'
    from_date:
      type: string
      label: 'Date From'
    to_date:
      type: string
      label: 'Date To'
    source:
      type: string
      label: 'Source'
    entity_types:
      type: sequence
      label: 'Entity types'
      sequence:
        type: string
        label: 'Entity type'
    bundles:
      type: sequence
      label: 'Entity bundles'
      sequence:
        type: string
        label: 'Entity bundle'
    tags:
      type: string
      label: 'Tags'
    author:
      type: integer
      label: 'Author'
