<?php

/**
 * @file
 * Contains ucsf_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ucsf_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ucsf_google_search module.
    case 'help.page.ucsf_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UCSF Search') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements HOOK_theme() to define all templates needed
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function ucsf_search_theme($existing, $type, $theme, $path) {
  return [
    'ucsf_universal_search' => [
      'variables' => [
        'results' => NULL,
        'directory' => NULL,
        'websites' => NULL,
        'searchterm' => NULL
      ],
    ],
    'ucsf_directory_search' => [
      'variables' => [
        'results' => NULL,
        'directory' => NULL,
        'searchterm' => NULL
      ],
    ],
    'ucsf_websites_search' => [
      'variables' => [
        'results' => NULL,
        'websites' => NULL,
        'searchterm' => NULL
      ],
    ]
  ];
}

/**
 * Implements hook_cron().
 */
function ucsf_search_cron() {

}
